### PR TITLE
Bump to JMS v3

### LINKED ISSUE #13: jms/serializer v3.0 support
v3.0 of [jms/serializer](https://github.com/schmittjoh/serializer/releases) has been out for a few days now. Are there plans to support this version?

### PR DESCRIPTION
**Pull request by simPod**
No problems found so far

Resolves #13

### CODE REVIEW

**Comment by simPod** [comment]
@VasekPurchart hi, any chance you could look at this?

**Comment by VasekPurchart** [comment]
Hi, thanks for the PR and sorry for the delay, I was really busy past few months, but is is starting to look better now, so I hope I will have a chance to look at the new version next week.

**Comment by Namoshek** [comment]
Can we at least have this merged in a development branch, so we don't need to reference a fork in the composer.json?

**Comment by hojgr** [comment]
We've been using this PR's fork for a few months without any issues. Everything seems to work.

**Comment by hojgr** [comment]
Another month without issues. Are there any plans to merge this or should we publish a fork on packagist?

**Comment by VasekPurchart** [comment]
Yes, there are plans to do so, but unfortunately unpredictable real life events - health issues of a close person - put stop to my plans for a while. Hope I will be getting back on track soon.

**Comment by VasekPurchart** [comment]
And btw thanks for testing, I appreciate that.

**Comment by enumag** [comment]
@VasekPurchart would you like some help with maintenance? I'm waiting for this PR as well.

**Comment by enumag** [comment]
@simPod @hojgr Do you guys have a forked version of https://github.com/consistence/consistence-jms-serializer-symfony that would allow installation of `consistence/consistence-jms-serializer` with this PR?

**Comment by simPod** [comment]
@enumag I'm using my forks, yes

```
        "consistence/consistence": "^2.0.1",
        "consistence/consistence-doctrine": "^2.0",
        "consistence/consistence-doctrine-symfony": "dev-newdeps@dev",
        "consistence/consistence-jms-serializer": "dev-bump as 2.1",
        "consistence/consistence-jms-serializer-symfony": "dev-symfony-5@dev",
```

I hope to drop consistence soon tho.

**Comment by enumag** [comment]
@simPod what are you replacing consistence enums with?

**Comment by simPod** [comment]
I'm considering to go with https://github.com/myclabs/php-enum However, I have had to build a small boilerplate around it. I have rework ready in a side branch, wanted to revisit it at least one more time yet and see if it's feasible enough.

**Comment by enumag** [comment]
@simPod Couldn't find any decent integration between `myclabs/php-enum` and `jms/serializer`. All the bundles require registration of every enum in YAML config and also are somewhat outdated and don't allow the latest versions of jms / symfony / doctrine or whatever. How did you solve that?

**Comment by simPod** [comment]
@enumag So far I copied this handler and modified it for php-enum

**Comment by enumag** [comment]
@simPod Yeah. I was thinking of doing exactly that. Mind sharing a gist?

**Pull request closed without merging**
